from loonybin import Tool

class Combine(Tool):
    
    def getName(self):
        return 'Machine Translation/Grammars and Tables/Chaski (Hadoop)/Score Phrases'
    
    def getDescription(self):
        return "Score phrase pairs with lexicon translaiton features, phrase translation features and reordering features "
    
    def getRequiredPaths(self):
        return ['chaski']

    def getParamNames(self):
        return [ ('avg-lex-score','By default Moses uses the most common alignment of the phrase pair to calculate lexical translation feature, specify this to use all alignments and average the score'),
                 ('true-align','Whether the alignment between two phrases will be output'),
                 ('num-mapper', 'Total number of available mapper slots'),
                 ('num-reducer', 'Total number of available reducer slots'),
                 ('map-per-node','Number of mappers per node, it may be ignored if your cluster does not allow you to change it'),
                 ('red-per-node','Number of reducers per node, it may be ignored if your cluster does not allow you to change it'),
                 ('queues', 'Specify the queue that the MR-Job will be submitted, if not specified, a warning will be displayed but the execution will continue'),
                 ('heap', 'Specify how much memory should each children task (Map/Reduce) use, default is 1024m'),
                 ]
    
    def getInputNames(self, params):
        return [ ('hdfs:lexicon','The lexicon generated by Build Lexicon tool'),
                 ('hdfs:extractedPhrases','Extracted phrases') ]

    def getOutputNames(self, params):
        return [ ('hdfs:combinedTable', 'Combined phrase and reorder table') ]
    
    def getCommands(self, params, inputs, outputs):
        paramString = ' '.join('--%s %s'%(key,value) for (key,value) in params.iteritems())
        cmd = ('hadoop jar chaski-0.0-latest.jar score --overwrite true --phrase %(hdfs:extractedPhrases)s '%inputs+
                 ' --lexicon %(hdfs:lexicon)s'%inputs+
                 ' --ptable %(hdfs:combinedTable)s '%outputs+
                 paramString)
        return ['hadoop dfs -cp %(hdfs:lexicon)s '%inputs + '%(hdfs:)s'%outputs,
                'hadoop dfs -cp %(hdfs:extractedPhrases)s '%inputs + '%(hdfs:)s'%outputs,
                cmd]

    def getPostAnalyzers(self, params, inputs, outputs):
        return [ ]

if __name__ == '__main__':
    import sys
    t = Combine()
    t.handle(sys.argv)
